services:
  mysql:
    image: mysql:8.0
    container_name: pw-nis2-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nis2_acn_registry
      MYSQL_USER: nis2_user
      MYSQL_PASSWORD: nis2pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --default-authentication-plugin=caching_sha2_password

volumes:
  mysql_data:
